#!/usr/bin/php
<?php
/**
 * Ce programme permet de convertir un nombre binaire en nombre décimal, 
 * tous deux représentés sous forme de chaines de caractères.
 * Approche avec une fonction de conversion procédurale
 */

declare(strict_types=1);

require 'vendor/autoload.php';

use Paul\Calculators\BinaryToDecimalConvertor;

///On définit un gestionnaire d'exception global
set_exception_handler(function (Throwable $exception) {
    echo $exception->getMessage() . PHP_EOL;
    echo "Fin du programme." . PHP_EOL;
});


///On vérifie que le nombre binaire est passé en argument de la commande
if (!isset($argv[1]))
    throw new Exception("Vous devez fournir un nombre binaire à convertir en argument du programme");

$binaryNumber = $argv[1];

/**
 * On vérifie que la représentation en chaîne de caractères 
 * du nombre binaire est bien formée (contient uniquement des 0 ou des 1)
 */

$converter = new BinaryToDecimalConvertor();

if (!$converter->isAValidBinaryNumber($binaryNumber)) {
    throw new Exception("Le nombre binaire est mal formé. Il ne doit contenir que des 0 ou des 1");
}

$decimalNumber = $converter->convertToDecimalProcedural($binaryNumber);

echo "Le nombre {$binaryNumber} en base 2 vaut {$decimalNumber} en base 10" . PHP_EOL;
