#!/usr/bin/php
<?php
/**
 * Ce programme permet de convertir un nombre binaire en nombre décimal, 
 * tous deux représentés sous forme de chaines de caractères.
 * Approche avec une fonction de conversion récursive
 */

declare(strict_types=1);

require 'vendor/autoload.php';

use Paul\Calculators\BinaryToDecimalConvertor;

///On définit un gestionnaire d'exception global
set_exception_handler(function (Throwable $exception) {
    echo $exception->getMessage() . PHP_EOL;
    echo "Fin du programme." . PHP_EOL;
});

//Début du programme

$binaryNumber = $argv[1];

$converter = new BinaryToDecimalConvertor();

/**
 * On vérifie que la représentation en chaîne de caractères 
 * du nombre binaire est bien formée (contient uniquement des 0 ou des 1)
 */
if (!$converter->isAValidBinaryNumber($binaryNumber)) {
    throw new Exception("Le nombre binaire est mal formé. Il ne doit contenir que des 0 ou des 1");
}

echo $converter->convertToDecimalRecursive($binaryNumber) . PHP_EOL;
